### PR TITLE
Feat/make cli init auto intall in project

### LINKED ISSUE #275: Make the CLI init command handle auto-install in project
Currently, the CLI search for main file to import and call the function and install Capgo.

It could be better to have it check for the most common usecase for :
- Nuxtjs
- NextJs
- SvelteKit
- vue
- react
- svelte

And be able to auto find the main file and add the required line in the project.

### PR DESCRIPTION
**Pull request by Mubashirshariq**
fixes #275 
/claim #275
Added the cli init  auto install for the following setups 

- Nuxtjs
- NextJs
- SvelteKit
- vue
- react
- svelte

### CODE REVIEW

**Comment by riderx** [comment]
Can you record a video demo?

**Comment by Mubashirshariq** [comment]
@riderx I will do that,but could you please you tell me  how I shoud test it on a project e.g, react ,i didn't find it in docs

**Comment by Mubashirshariq** [comment]
@riderx  could you please share the exact link/part of the docs where i can find the instruction regarding testing it on a project

**Comment by riderx** [comment]
You have the explanation of how people should install manually:
https://capgo.app/docs/plugin/cloud-mode/auto-update/
Testing a project i think will be harder as you need to create empty project and add capacitor in it

**Comment by Mubashirshariq** [comment]
Yeah i understood the manual intallation that is why i added finding the project type and if the project is using javascript or typescript based on that decided the entry point/main file and injected the required code in it.But you were telling to record a video that is what i was asking how i should  test it?

**Comment by riderx** [comment]
Just demo your code, you create a svelte project and you run the CLI and we see in the video the import is in the code, the package got installed.
And the project run in web, and we see in the console it say it do nothing in web. ( the plugin will  say it by itself)
That will be enough.
For each platform you implement:)

**Comment by riderx** [comment]
I realize it a bit of work so I will upgrade the bounty

**Comment by Mubashirshariq** [comment]
@riderx  i am sharing the video for svelte.Could you please see and let me know is this the thing you wanted me to do,so that then i  can make the demo video of other setups

[Screencast from 2024-07-08 23-56-16.webm](https://github.com/Cap-go/CLI/assets/103755591/6983e1f9-6d78-4d96-b0f6-bb64640dd666)

**Comment by riderx** [comment]
Perfect!

**Comment by Mubashirshariq** [comment]
[Screencast from 2024-07-09 00-58-47.webm](https://github.com/Cap-go/CLI/assets/103755591/371c534e-5f77-4287-9485-f4655d2d24b9)

this is for react,but latest nextjs has somewhat different structure compared to previous version ,so i wll write the logic based on  the version and try to set the main file based on that

**Comment by Mubashirshariq** [comment]
1)vue typescript

[vuetypescript.webm](https://github.com/Cap-go/CLI/assets/103755591/fdd4b407-1f96-4707-a0df-55355c99d72e)

2)vue javascript

[vueJavascript.webm](https://github.com/Cap-go/CLI/assets/103755591/3a4e140e-149a-4d55-b1c2-3952440e0610)

3)nextjs typescript

[nextjs-typescript.webm](https://github.com/Cap-go/CLI/assets/103755591/9ef132d4-a976-4d87-8644-9165449e5f2a)

4)nextjs javascript

[nextjs_javascript.webm](https://github.com/Cap-go/CLI/assets/103755591/65a07b1c-5166-45b3-8426-1b41a2652d52)

**Comment by Mubashirshariq** [comment]
@riderx i had added testing of all except nuxtjs and displaying errors in case people are not using latest versions proper errors ,i will push the changes that i did while testing also but for nuxt js the structure is somewhat like this index.vue.so where i should i inject the required code 

Screenshot from 2024-07-09 20-16-05

**Comment by riderx** [comment]
Nice man, thanks a lot for that !

**Comment by riderx** [comment]
i think the best for nuxt is to add a custom plugin :
https://nuxt.com/docs/guide/directory-structure/plugins

**Comment by Mubashirshariq** [comment]
@riderx  so we have to just create one folder  with name plugins inside that we will create  file named capacitorUpdater.ts and inside that we will inject that code which we  were earlier injecting in the entry  points of other files, and nuxt will automatically load that plugin at the creation of the application

**Comment by riderx** [comment]
yes with 2 point to note:
- the folder can already exist if the user is installing in app who exist, so you need to check if exist
- The plugin code is a bit more complex than just having the import, so if you use what is in the doc and make it only client side it should be good !

**Comment by Mubashirshariq** [comment]
@riderx  is this the code you are talking about https://capgo.app/docs/plugin/cloud-mode/manual-update/

**Comment by riderx** [comment]
No, i'm talking about a Nuxt plugin:
```js
import { CapacitorUpdater } from '@capgo/capacitor-updater'

export default defineNuxtPlugin(() => {
 	CapacitorUpdater.notifyAppReady()
})
```
And the plugin name file should be something like `capacitorUpdater.client.ts` to be sure it only run on client side

**Comment by Mubashirshariq** [comment]
@riderx  i have pushed all the changes and here is the test video for nuxtjs

[nuxttest.webm](https://github.com/Cap-go/CLI/assets/103755591/0ade61b7-8b43-4e8e-bc88-1c97f4629942)

**Comment by riderx** [comment]
This is nice!
I think just for nuxt we have to take in account if the project is in JS the plugin should be JS too

**Comment by Mubashirshariq** [comment]
so the file name should be capacitorUpdater.client.js for javascript  other things will remain same

**Comment by Mubashirshariq** [comment]
nuxtjs javascript 

[nuxtjavascript.webm](https://github.com/Cap-go/CLI/assets/103755591/f93e9b3f-d9af-4dd2-b634-2bbd49cf540f)

**Comment by riderx** [comment]
Perfect did you runned the lint command?

**Comment by riderx** [comment]
I think you need to pull main in your branch that will fix it

**Comment by Mubashirshariq** [comment]
@riderx  done!

**Comment by Mubashirshariq** [comment]
@riderx i have made the required changes !

**Comment by riderx** [comment]
Hey @Mubashirshariq i just got a report of one user with this project folder:
image
he got this error:
●  Found angular project
◇  Error
│
▲  Cannot find the latest version of angular-ts, you might need to upgrade to the latest version of angular-ts
│
└  Bye 👋
Any clue why this happens ?

**Comment by Mubashirshariq** [comment]
@riderx  I will look into it

**Pull request merged**
