### PR TITLE
Add json logger

### PR DESCRIPTION
**Pull request by fxsalazar**
Abstraction of the json logs.

My motivation was to avoid printing the `checkLatest` warning when --json

### CODE REVIEW

**Comment by fxsalazar** [comment]
👀  any news for this PR?

**Comment by fxsalazar** [comment]
@riderx can it be possible to at least avoid printing the checkLatest when using --json

**Comment by riderx** [comment]
Sorry it seems i closed wrongly, i check it again

**Comment by riderx** [comment]
Thanks a lot for trying, I just made a solution i was finding simpler: 
https://github.com/Cap-go/CLI/commit/540363461a6d2410e8e3130d70a0b0def2186c9f

**Comment by fxsalazar** [comment]
For abstraction; instead of checking everywhere you wan to print `if (!json)`, let the Logger handle how do the logging.

**Comment by riderx** [comment]
This option is only available in one place, and if the message is not print there is no need to call `checkLatest` so i went the simple way and add one more if instead :)

**Pull request closed without merging**
