### PR TITLE
Returned the bundle URL from upload command

### LINKED ISSUE #116: Return the bundle URL from upload command
When user upload, it could be nice if he had the link to the bundle in the webapp

### PR DESCRIPTION
**Pull request by MAYANK-TRIPATH**
Fixes #116 
/claim #116

### CODE REVIEW

**Comment by riderx** [comment]
Thanks for this !
That great job, one thing I should have to make clear is, this URL should be usable by another command, like for example you use upload command in your CI and you want to send to a Slack channel the URL the command returned

**Comment by MAYANK-TRIPATH** [comment]
@riderx Thanks for clearing requirement,  I make required changes please look into it.

**Comment by riderx** [comment]
Thanks for the update, can you document how can this URL can be retrieved as variable for another script, I'm not sure to understand

**Comment by MAYANK-TRIPATH** [comment]
We have `uploadCommand` and `uploadDeprecatedCommand` function, after calling the `uploadBundle function` , the returned `bundleLink` URL is stored in the `bundleLink` variable. Then, the URL is logged to the console using `p.log.info()`.
Using same approach use the `bundleLink` URL in another script or context. Simply call the `uploadBundle` function and retrieve the `bundleLink` URL from the returned value.

**Comment by MAYANK-TRIPATH** [comment]
@riderx If you want me to add comments in the code, let me know i can do that too.

**Comment by riderx** [comment]
@MAYANK-TRIPATH thanks for the explanation.
While I understand your explanation, I believe you didn't understand my request.

User has to use the CLI he wants to be able to get the URL in an env var or something simple that he can use in next GitHub action or next command. Parsing the output is not convenient.
Or at least if you provide a clear explain in the doc how to do it with the regex etc

**Comment by MAYANK-TRIPATH** [comment]
@riderx Sorry for confusion.
As far as i understand You're  looking to generate a URL for the uploaded bundle and potentially use it in different contexts, such as CI/CD pipelines or Slack notifications.
let me know if i am missing something.

**Comment by riderx** [comment]
Yes you are right but both step will be done in CI/CD the upload and the slack notif.
So upload command should set env or return the URL in easy way for the next CI step

**Comment by riderx** [comment]
Right now i don't have clue in your changes how the next step will be able to get the URL

**Comment by MAYANK-TRIPATH** [comment]
Sorry for late reply, actually college exams.
For now closing this PR and will do fresh start :)

**Pull request closed without merging**
